export type ThemeName = 'dark' | 'light' | 'green';

export interface Theme {
  name: ThemeName;
  // Tła
  bg: string;
  surface: string;
  surface2: string;
  surface3: string;
  // Obramowania
  border: string;
  // Teksty
  text: string;
  textSub: string;
  textMuted: string;
  // Akcent
  accent: string;
  accentDark: string;
  accentLight: string;
  accentText: string;
  // Statusy
  success: string;
  successBg: string;
  warning: string;
  warningBg: string;
  danger: string;
  dangerBg: string;
  info: string;
  infoBg: string;
  // Header
  headerBg: string;
  headerText: string;
  headerSub: string;
  // Nawigacja
  navBg: string;
  navActive: string;
  navInactive: string;
  navBorder: string;
  // Karty
  cardBg: string;
  cardBorder: string;
  // Input
  inputBg: string;
  inputBorder: string;
  inputText: string;
  inputPlaceholder: string;
  // Układ i typografia (wspólne)
  radiusXs: number;
  radiusSm: number;
  radiusMd: number;
  radiusLg: number;
  radiusXl: number;
  fontScreenTitle: number;
  fontSection: number;
  fontBody: number;
  fontCaption: number;
  fontMicro: number;
  // Cień kart (React Native)
  shadowColor: string;
  shadowOpacity: number;
  shadowRadius: number;
  shadowOffsetY: number;
  cardElevation: number;
  /** Wykresy / odznaki ról (dodatkowy akcent) */
  chartViolet: string;
  chartCyan: string;
}

export const themes: Record<ThemeName, Theme> = {
  dark: {
    name: 'dark',
    bg: '#0B0F14',
    surface: '#121826',
    surface2: '#1A2234',
    surface3: '#232F45',
    border: '#2D3A4F',
    text: '#F4F6F8',
    textSub: '#A8B3C4',
    textMuted: '#6B778C',
    accent: '#2DD4BF',
    accentDark: '#14B8A6',
    accentLight: '#134E4A',
    accentText: '#042F2E',
    success: '#34D399',
    successBg: '#064E3B',
    warning: '#FBBF24',
    warningBg: '#422006',
    danger: '#F87171',
    dangerBg: '#3F0E0E',
    info: '#60A5FA',
    infoBg: '#1E3A5F',
    headerBg: '#121826',
    headerText: '#F4F6F8',
    headerSub: '#8B95A8',
    navBg: '#121826',
    navActive: '#2DD4BF',
    navInactive: '#6B778C',
    navBorder: '#2D3A4F',
    cardBg: '#121826',
    cardBorder: '#2D3A4F',
    inputBg: '#1A2234',
    inputBorder: '#2D3A4F',
    inputText: '#F4F6F8',
    inputPlaceholder: '#6B778C',
    radiusXs: 6,
    radiusSm: 8,
    radiusMd: 12,
    radiusLg: 14,
    radiusXl: 18,
    fontScreenTitle: 22,
    fontSection: 16,
    fontBody: 15,
    fontCaption: 12,
    fontMicro: 11,
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffsetY: 3,
    cardElevation: 4,
    chartViolet: '#A78BFA',
    chartCyan: '#22D3EE',
  },

  light: {
    name: 'light',
    bg: '#F1F3F5',
    surface: '#FFFFFF',
    surface2: '#F4F6F8',
    surface3: '#E8ECF0',
    border: '#D8DEE6',
    text: '#0F172A',
    textSub: '#475569',
    textMuted: '#94A3B8',
    accent: '#4338CA',
    accentDark: '#3730A3',
    accentLight: '#EEF2FF',
    accentText: '#FFFFFF',
    success: '#059669',
    successBg: '#D1FAE5',
    warning: '#D97706',
    warningBg: '#FEF3C7',
    danger: '#DC2626',
    dangerBg: '#FEE2E2',
    info: '#2563EB',
    infoBg: '#DBEAFE',
    headerBg: '#FFFFFF',
    headerText: '#0F172A',
    headerSub: '#64748B',
    navBg: '#FFFFFF',
    navActive: '#4338CA',
    navInactive: '#94A3B8',
    navBorder: '#E2E8F0',
    cardBg: '#FFFFFF',
    cardBorder: '#E2E8F0',
    inputBg: '#F8FAFC',
    inputBorder: '#D8DEE6',
    inputText: '#0F172A',
    inputPlaceholder: '#94A3B8',
    radiusXs: 6,
    radiusSm: 8,
    radiusMd: 12,
    radiusLg: 14,
    radiusXl: 18,
    fontScreenTitle: 22,
    fontSection: 16,
    fontBody: 15,
    fontCaption: 12,
    fontMicro: 11,
    shadowColor: '#0F172A',
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffsetY: 2,
    cardElevation: 2,
    chartViolet: '#6D28D9',
    chartCyan: '#0891B2',
  },

  green: {
    name: 'green',
    bg: '#F1F3F5',
    surface: '#FFFFFF',
    surface2: '#F4F6F8',
    surface3: '#E8ECF0',
    border: '#D1D5DB',
    text: '#111827',
    textSub: '#4B5563',
    textMuted: '#9CA3AF',
    accent: '#047857',
    accentDark: '#065F46',
    accentLight: '#ECFDF5',
    accentText: '#FFFFFF',
    success: '#059669',
    successBg: '#D1FAE5',
    warning: '#B45309',
    warningBg: '#FEF3C7',
    danger: '#B91C1C',
    dangerBg: '#FEE2E2',
    info: '#0369A1',
    infoBg: '#E0F2FE',
    headerBg: '#0F172A',
    headerText: '#FFFFFF',
    headerSub: '#9CA3AF',
    navBg: '#FFFFFF',
    navActive: '#047857',
    navInactive: '#9CA3AF',
    navBorder: '#E5E7EB',
    cardBg: '#FFFFFF',
    cardBorder: '#E5E7EB',
    inputBg: '#F9FAFB',
    inputBorder: '#D1D5DB',
    inputText: '#111827',
    inputPlaceholder: '#9CA3AF',
    radiusXs: 6,
    radiusSm: 8,
    radiusMd: 12,
    radiusLg: 14,
    radiusXl: 18,
    fontScreenTitle: 22,
    fontSection: 16,
    fontBody: 15,
    fontCaption: 12,
    fontMicro: 11,
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffsetY: 2,
    cardElevation: 2,
    chartViolet: '#5B21B6',
    chartCyan: '#0F766E',
  },
};

export const THEME_LABELS: Record<ThemeName, string> = {
  dark: 'Ciemny',
  light: 'Jasny',
  green: 'Korporacyjny',
};
