export default {
  tenants: [
    { id: 'tenant-pf', name: 'Polska Flora', plan: 'enterprise', status: 'active', defaultLanguage: 'pl' },
    { id: 'tenant-other', name: 'Drzewo Test Labs', plan: 'starter', status: 'active', defaultLanguage: 'pl' },
  ],
  planLimits: [
    {
      id: 'plan-starter',
      plan: 'starter',
      label: 'Starter',
      monthlyPriceNet: 399,
      limits: { users: 5, branches: 1, aiMinutes: 300, softphoneSeats: 2, storageGb: 25, automations: 5, mobileUsers: 3 },
      features: ['CRM i zlecenia', 'Podstawowy softphone', 'Portal klienta'],
    },
    {
      id: 'plan-growth',
      plan: 'growth',
      label: 'Growth',
      monthlyPriceNet: 1199,
      limits: { users: 25, branches: 3, aiMinutes: 2500, softphoneSeats: 10, storageGb: 150, automations: 30, mobileUsers: 20 },
      features: ['AI recepcjonista', 'Nagrania i transkrypcje', 'Workflow builder', 'Dokumenty HR'],
    },
    {
      id: 'plan-enterprise',
      plan: 'enterprise',
      label: 'Enterprise',
      monthlyPriceNet: 2999,
      limits: { users: 250, branches: 25, aiMinutes: 25000, softphoneSeats: 80, storageGb: 2000, automations: 250, mobileUsers: 200 },
      features: ['Multi-tenant', 'SLA i audyt', 'Zaawansowany AI coaching', 'Priorytetowe integracje'],
    },
  ],
  tenantSubscriptions: [
    {
      id: 'sub-tenant-pf',
      tenantId: 'tenant-pf',
      plan: 'enterprise',
      status: 'active',
      billingProvider: 'przelewy24',
      currentPeriodStart: '2026-06-01T00:00:00.000Z',
      currentPeriodEnd: '2026-07-01T00:00:00.000Z',
      seats: 18,
      aiMinutesUsed: 1840,
      storageGbUsed: 82,
      nextInvoiceNet: 2999,
      updatedAt: '2026-06-01T09:00:00.000Z',
      updatedBy: 'u-admin',
    },
    {
      id: 'sub-tenant-other',
      tenantId: 'tenant-other',
      plan: 'starter',
      status: 'active',
      billingProvider: 'manual',
      currentPeriodStart: '2026-06-01T00:00:00.000Z',
      currentPeriodEnd: '2026-07-01T00:00:00.000Z',
      seats: 2,
      aiMinutesUsed: 12,
      storageGbUsed: 3,
      nextInvoiceNet: 399,
      updatedAt: '2026-06-01T09:00:00.000Z',
      updatedBy: 'u-other-admin',
    },
  ],
  billingPayments: [
    {
      id: 'pay-tenant-pf-001',
      tenantId: 'tenant-pf',
      subscriptionId: 'sub-tenant-pf',
      provider: 'przelewy24',
      status: 'paid',
      amountNet: 2999,
      currency: 'PLN',
      description: 'Arbor OS Enterprise - czerwiec 2026',
      createdAt: '2026-06-01T09:00:00.000Z',
      paidAt: '2026-06-01T09:03:00.000Z',
      externalId: 'P24-DEMO-001',
      checkoutUrl: 'https://secure.przelewy24.pl/trnRequest/P24-DEMO-001',
    },
  ],
  integrationSettings: [
    {
      id: 'int-tenant-pf',
      tenantId: 'tenant-pf',
      zadarma: {
        enabled: true,
        autoCreateCommunication: true,
        autoAttachRecordings: true,
        autoAnalyzeRecordings: true,
        recordingRetentionDays: 90,
        requireRecordingConsent: true,
      },
      ai: {
        provider: 'openai',
        speechToText: 'deepgram',
        autoTranscribe: true,
        autoAnalyze: true,
        redactPii: true,
        humanApprovalRequiredBelowScore: 75,
      },
      messaging: {
        smsProvider: 'smsapi',
        emailProvider: 'aws_ses',
        sendBookingConfirmations: true,
        sendMissedCallFollowups: true,
      },
      maps: {
        provider: 'google_maps',
        routeOptimization: true,
      },
      monitoring: {
        sentryEnabled: true,
        auditRetentionDays: 365,
      },
      updatedAt: '2026-06-01T09:00:00.000Z',
      updatedBy: 'u-admin',
    },
    {
      id: 'int-tenant-other',
      tenantId: 'tenant-other',
      zadarma: {
        enabled: false,
        autoCreateCommunication: false,
        autoAttachRecordings: false,
        autoAnalyzeRecordings: false,
        recordingRetentionDays: 30,
        requireRecordingConsent: true,
      },
      ai: {
        provider: 'local',
        speechToText: 'manual',
        autoTranscribe: false,
        autoAnalyze: false,
        redactPii: true,
        humanApprovalRequiredBelowScore: 90,
      },
      messaging: {
        smsProvider: 'manual',
        emailProvider: 'manual',
        sendBookingConfirmations: false,
        sendMissedCallFollowups: false,
      },
      maps: {
        provider: 'manual',
        routeOptimization: false,
      },
      monitoring: {
        sentryEnabled: false,
        auditRetentionDays: 90,
      },
      updatedAt: '2026-06-01T09:00:00.000Z',
      updatedBy: 'u-other-admin',
    },
  ],
  communications: [
    {
      id: 'com-1',
      type: 'call',
      clientId: 'c-1',
      orderId: 'Z-1024',
      userId: 'u-manager',
      direction: 'inbound',
      channel: 'web_softphone',
      status: 'completed',
      subject: 'Telefon o termin oględzin i zakres prac',
      startedAt: '2026-08-29T09:12:00.000Z',
      durationSec: 412,
      aiHandled: false,
      recordingUrl: '/recordings/demo/com-1.mp3',
      transcript: [
        { speaker: 'Klient', text: 'Chcemy przyciąć korony drzew przy parkingu i ustalić termin oględzin.', atSec: 12 },
        { speaker: 'Biuro', text: 'Umówię wyceniającego i potwierdzę SMS z dokładną godziną.', atSec: 38 },
      ],
      analysis: {
        score: 88,
        summary: 'Biuro przejęło rozmowę, ustaliło potrzebę oględzin i termin kontaktu.',
        intent: 'Pielęgnacja koron i oględziny osiedla',
        strengths: ['Szybkie ustalenie potrzeby', 'Jasny następny krok'],
        improvements: ['Dopytać o utrudnienia parkingowe'],
        nextActions: ['Potwierdzić oględziny SMS', 'Przypisać wyceniającego'],
        risks: ['Prace przy parkingu wymagają zabezpieczenia terenu'],
      },
    },
    {
      id: 'com-2',
      type: 'meeting',
      clientId: 'c-2',
      orderId: 'Z-1025',
      userId: 'u-est',
      direction: 'outbound',
      channel: 'mobile_meeting',
      status: 'completed',
      subject: 'Spotkanie terenowe przy świerku',
      startedAt: '2026-09-05T12:00:00.000Z',
      durationSec: 1260,
      aiHandled: false,
      recordingUrl: '/recordings/demo/com-2.m4a',
      transcript: [
        { speaker: 'Wyceniający', text: 'Drzewo jest blisko ogrodzenia, potrzebna będzie asekuracja linowa.', atSec: 54 },
        { speaker: 'Klient', text: 'Proszę doliczyć wywóz gałęzi i uporządkowanie ogrodu.', atSec: 112 },
      ],
      analysis: {
        score: 91,
        summary: 'Spotkanie zebrano poprawnie: zakres, ryzyka i dodatkowa usługa wywozu.',
        intent: 'Wycinka sekcyjna z wywozem',
        strengths: ['Dobrze opisane ryzyko', 'Zebrano dodatkową usługę'],
        improvements: ['Dodać zdjęcie dostępu dla rębaka'],
        nextActions: ['Wysłać wycenę do biura', 'Zarezerwować rębak'],
        risks: ['Bliskość ogrodzenia', 'Ograniczony dostęp sprzętu'],
      },
    },
    {
      id: 'com-3',
      type: 'call',
      clientId: 'c-4',
      direction: 'inbound',
      channel: 'ai_receptionist',
      status: 'completed',
      subject: 'AI recepcjonista po godzinach',
      startedAt: '2026-09-05T18:42:00.000Z',
      durationSec: 238,
      aiHandled: true,
      recordingUrl: '/recordings/demo/com-3.mp3',
      transcript: [
        { speaker: 'AI recepcjonista', text: 'Dzień dobry, Polska Flora. Pomogę umówić oględziny.', atSec: 0 },
        { speaker: 'Klient', text: 'Chodzi o frezowanie pnia i wywóz odpadów.', atSec: 19 },
      ],
      analysis: {
        score: 84,
        summary: 'AI zakwalifikował klienta, zebrał zakres i zaproponował termin oględzin.',
        intent: 'Frezowanie pnia',
        strengths: ['Spokojne zebranie danych', 'Ustalony termin'],
        improvements: ['Dopytać o średnicę pnia'],
        nextActions: ['Potwierdzić termin SMS', 'Utworzyć zadanie dla biura'],
        risks: ['Brak zdjęcia pnia'],
      },
    },
  ],
  softphonePresence: [],
  aiPrompts: [
    {
      id: 'prompt-1',
      tenantId: 'tenant-pf',
      name: 'Analiza rozmowy biura',
      kind: 'office_call',
      version: 3,
      status: 'active',
      body: 'Oceń rozmowę biura z klientem. Zwróć JSON: score, summary, intent, strengths, improvements, risks, nextActions.',
      updatedAt: '2026-09-01T08:00:00.000Z',
      updatedBy: 'u-admin',
    },
    {
      id: 'prompt-2',
      tenantId: 'tenant-pf',
      name: 'AI recepcjonista po godzinach',
      kind: 'ai_receptionist',
      version: 1,
      status: 'active',
      body: 'Zbierz dane klienta, lokalizację, typ prac, pilność i preferowany termin oględzin. Eskaluj pilne zagrożenia.',
      updatedAt: '2026-09-01T08:10:00.000Z',
      updatedBy: 'u-admin',
    },
    {
      id: 'prompt-3',
      tenantId: 'tenant-pf',
      name: 'Spotkanie wyceniającego',
      kind: 'field_meeting',
      version: 2,
      status: 'active',
      body: 'Podsumuj spotkanie terenowe, ryzyka, potrzebny sprzęt, propozycje pozycji wyceny i następne kroki.',
      updatedAt: '2026-09-01T08:20:00.000Z',
      updatedBy: 'u-est',
    },
    {
      id: 'prompt-other-1',
      tenantId: 'tenant-other',
      name: 'Ukryty prompt tenant other',
      kind: 'office_call',
      version: 1,
      status: 'active',
      body: 'Prompt izolacyjny dla drugiego tenanta. Nie powinien być widoczny dla Polska Flora.',
      updatedAt: '2026-09-01T08:20:00.000Z',
      updatedBy: 'u-other-admin',
    },
  ],
  aiPromptVersions: [
    {
      id: 'prompt-1-v3',
      tenantId: 'tenant-pf',
      promptId: 'prompt-1',
      version: 3,
      status: 'active',
      body: 'Oceń rozmowę biura z klientem. Zwróć JSON: score, summary, intent, strengths, improvements, risks, nextActions.',
      changeNote: 'Wersja startowa demo',
      createdAt: '2026-09-01T08:00:00.000Z',
      createdBy: 'u-admin',
    },
    {
      id: 'prompt-2-v1',
      tenantId: 'tenant-pf',
      promptId: 'prompt-2',
      version: 1,
      status: 'active',
      body: 'Zbierz dane klienta, lokalizację, typ prac, pilność i preferowany termin oględzin. Eskaluj pilne zagrożenia.',
      changeNote: 'Wersja startowa demo',
      createdAt: '2026-09-01T08:10:00.000Z',
      createdBy: 'u-admin',
    },
    {
      id: 'prompt-3-v2',
      tenantId: 'tenant-pf',
      promptId: 'prompt-3',
      version: 2,
      status: 'active',
      body: 'Podsumuj spotkanie terenowe, ryzyka, potrzebny sprzęt, propozycje pozycji wyceny i następne kroki.',
      changeNote: 'Wersja startowa demo',
      createdAt: '2026-09-01T08:20:00.000Z',
      createdBy: 'u-est',
    },
    {
      id: 'prompt-other-1-v1',
      tenantId: 'tenant-other',
      promptId: 'prompt-other-1',
      version: 1,
      status: 'active',
      body: 'Prompt izolacyjny dla drugiego tenanta. Nie powinien być widoczny dla Polska Flora.',
      changeNote: 'Wersja startowa testu izolacji',
      createdAt: '2026-09-01T08:20:00.000Z',
      createdBy: 'u-other-admin',
    },
  ],
  aiBotSessions: [
    {
      id: 'bot-1',
      clientId: 'c-4',
      mode: 'after_hours',
      status: 'booked',
      startedAt: '2026-09-05T18:42:00.000Z',
      transcript: 'Klient prosi o frezowanie pnia. AI zebrał adres, zakres i preferowany termin.',
      outcome: 'Utworzono lead i zadanie dla biura, zaproponowano oględziny 09.09 09:30.',
      inspectionAt: '2026-09-09T09:30:00.000Z',
      orderId: 'Z-1027',
    },
  ],
  aiReceptionistSettings: [
    {
      id: 'ai-rec-default',
      tenantId: 'tenant-pf',
      enabled: true,
      mode: 'full_booking',
      businessHours: [
        { day: 'mon', open: '08:00', close: '17:00', active: true },
        { day: 'tue', open: '08:00', close: '17:00', active: true },
        { day: 'wed', open: '08:00', close: '17:00', active: true },
        { day: 'thu', open: '08:00', close: '17:00', active: true },
        { day: 'fri', open: '08:00', close: '16:00', active: true },
        { day: 'sat', open: '09:00', close: '13:00', active: false },
        { day: 'sun', open: '09:00', close: '13:00', active: false },
      ],
      overflowAfterSec: 25,
      bookingWindowDays: 21,
      escalationRules: ['zagrożenie życia lub mienia', 'klient strategiczny', 'reklamacja po realizacji'],
      qualificationQuestions: ['lokalizacja prac', 'typ drzewa lub usługi', 'pilność', 'zdjęcia', 'preferowany termin oględzin'],
      language: 'pl',
      updatedAt: '2026-09-01T08:30:00.000Z',
      updatedBy: 'u-admin',
    },
    {
      id: 'ai-rec-other',
      tenantId: 'tenant-other',
      enabled: false,
      mode: 'after_hours',
      businessHours: [
        { day: 'mon', open: '09:00', close: '15:00', active: true },
        { day: 'tue', open: '09:00', close: '15:00', active: true },
      ],
      overflowAfterSec: 45,
      bookingWindowDays: 7,
      escalationRules: ['tenant-other escalation'],
      qualificationQuestions: ['tenant-other question'],
      language: 'pl',
      updatedAt: '2026-09-01T08:30:00.000Z',
      updatedBy: 'u-other-admin',
    },
  ],
  workflows: [
    {
      id: 'wf-1',
      tenantId: 'tenant-pf',
      name: 'Nieodebrany telefon -> AI recepcjonista',
      trigger: 'call.missed',
      status: 'live',
      killSwitch: false,
      actions: ['Oddzwaniaj AI botem', 'Utwórz lead', 'Powiadom kierownika'],
      lastRunAt: '2026-09-05T18:42:00.000Z',
      runCount: 42,
      successRate: 95,
    },
    {
      id: 'wf-2',
      tenantId: 'tenant-pf',
      name: 'Wycena zaakceptowana -> ekipa i portal',
      trigger: 'valuation.approved',
      status: 'live',
      killSwitch: false,
      actions: ['Przypisz ekipę', 'Wyślij portal klienta', 'Zarezerwuj sprzęt'],
      lastRunAt: '2026-09-03T14:10:00.000Z',
      runCount: 18,
      successRate: 89,
    },
    {
      id: 'wf-other-1',
      tenantId: 'tenant-other',
      name: 'Ukryty workflow tenant other',
      trigger: 'tenant_other.test',
      status: 'paused',
      killSwitch: true,
      actions: ['Nie pokazuj Polska Flora'],
      lastRunAt: '2026-09-01T08:30:00.000Z',
      runCount: 1,
      successRate: 0,
    },
  ],
  workflowRuns: [
    { id: 'run-1', tenantId: 'tenant-pf', workflowId: 'wf-1', status: 'success', startedAt: '2026-09-05T18:42:00.000Z', log: ['Trigger call.missed', 'AI bot completed qualification', 'Task created for manager'] },
    { id: 'run-other-1', tenantId: 'tenant-other', workflowId: 'wf-other-1', status: 'failed', startedAt: '2026-09-01T08:30:00.000Z', log: ['Tenant other isolation fixture'] },
  ],
  tasks: [
    {
      id: 'task-1',
      tenantId: 'tenant-pf',
      title: 'Oddzwonić do klienta po nieodebranym telefonie',
      status: 'open',
      priority: 'high',
      source: 'workflow',
      sourceId: 'run-1',
      workflowId: 'wf-1',
      workflowRunId: 'run-1',
      clientId: 'c-4',
      branchId: 'krk',
      assignedUserId: 'u-manager',
      dueAt: '2026-09-05T19:00:00.000Z',
      notes: 'Zadanie utworzone automatycznie po kwalifikacji AI.',
      createdAt: '2026-09-05T18:42:00.000Z',
      createdBy: 'u-manager',
    },
    {
      id: 'task-other-1',
      tenantId: 'tenant-other',
      title: 'Ukryte zadanie tenant other',
      status: 'open',
      priority: 'normal',
      source: 'manual',
      branchId: 'oth',
      assignedUserId: 'u-other-admin',
      createdAt: '2026-09-01T08:30:00.000Z',
      createdBy: 'u-other-admin',
    },
  ],
  moduleConfigs: [
    {
      id: 'cfg-crm',
      tenantId: 'tenant-pf',
      module: 'crm',
      label: 'CRM',
      enabled: true,
      customFields: [{ key: 'segment', label: 'Segment', type: 'select' }, { key: 'source', label: 'Źródło leadu', type: 'select' }],
      statuses: ['lead', 'kwalifikacja', 'oględziny', 'oferta', 'wygrany', 'utracony'],
      requiredDocuments: ['Zgoda na kontakt', 'Oferta'],
    },
    {
      id: 'cfg-orders',
      tenantId: 'tenant-pf',
      module: 'orders',
      label: 'Zlecenia',
      enabled: true,
      customFields: [{ key: 'tree_count', label: 'Liczba drzew', type: 'number' }],
      statuses: ['NOWE', 'ZAPLANOWANE', 'W_REALIZACJI', 'ZAKONCZONE'],
      requiredDocuments: ['BHP', 'Podpis klienta', 'Zdjęcia przed/po'],
    },
    {
      id: 'cfg-other-crm',
      tenantId: 'tenant-other',
      module: 'crm',
      label: 'Ukryty CRM tenant other',
      enabled: true,
      customFields: [{ key: 'hidden', label: 'Hidden', type: 'text' }],
      statuses: ['tenant-other-only'],
      requiredDocuments: ['Tenant other document'],
    },
  ],
  documentTemplates: [
    {
      id: 'tpl-1',
      name: 'Umowa z pracownikiem terenowym',
      kind: 'contract',
      scope: 'employee',
      status: 'active',
      fields: ['employeeName', 'jobTitle', 'rate', 'branch', 'startDate'],
      body: 'Umowa dla {{employeeName}} na stanowisku {{jobTitle}} w oddziale {{branch}}.',
    },
    {
      id: 'tpl-2',
      name: 'Oferta prac arborystycznych',
      kind: 'offer',
      scope: 'order',
      status: 'active',
      fields: ['clientName', 'orderType', 'grossValue', 'validUntil'],
      body: 'Oferta dla {{clientName}}: {{orderType}}, wartość {{grossValue}}, ważna do {{validUntil}}.',
    },
  ],
  generatedDocuments: [
    {
      id: 'doc-1',
      templateId: 'tpl-2',
      subjectType: 'order',
      subjectId: 'Z-1025',
      status: 'ready',
      createdAt: '2026-09-05T13:20:00.000Z',
      createdBy: 'u-est',
      summary: 'Oferta dla Anny Zielińskiej po oględzinach terenowych.',
    },
  ],
  jobPositions: [
    {
      id: 'pos-1',
      title: 'Brygadzista arborystyczny',
      department: 'field',
      contractType: 'employment',
      rate: '8500 PLN brutto',
      responsibilities: ['Prowadzenie ekipy', 'BHP przed pracą', 'Dokumentacja zdjęciowa'],
      requiredDocuments: ['Badania wysokościowe', 'Szkolenie BHP', 'Uprawnienia pilarkowe'],
      requiredTraining: ['Ratownictwo drzewne', 'Praca na wysokości'],
    },
    {
      id: 'pos-2',
      title: 'Wyceniający terenowy',
      department: 'sales',
      contractType: 'b2b',
      rate: '12000 PLN netto',
      responsibilities: ['Oględziny', 'Nagrywanie spotkań', 'Przygotowanie wycen'],
      requiredDocuments: ['RODO', 'Umowa B2B', 'Prawo jazdy B'],
      requiredTraining: ['Standard rozmowy', 'AI coaching'],
    },
  ],
  documentRequirements: [
    { id: 'req-1', scope: 'employee', name: 'Badania wysokościowe', requiredFor: 'pos-1', renewEveryMonths: 12, warningDays: 30 },
    { id: 'req-2', scope: 'employee', name: 'Szkolenie BHP', requiredFor: 'all-field', renewEveryMonths: 12, warningDays: 45 },
    { id: 'req-3', scope: 'employee', name: 'Umowa B2B lub pracownicza', requiredFor: 'all', warningDays: 30 },
    { id: 'req-4', scope: 'equipment', name: 'OC sprzętu', requiredFor: 'fleet', renewEveryMonths: 12, warningDays: 30 },
  ],
  employeeContracts: [
    {
      id: 'contract-1',
      employeeId: 'u-lead',
      employeeName: 'Piotr Wrona',
      positionId: 'pos-1',
      branchId: 'krk',
      type: 'employment',
      status: 'active',
      startDate: '2026-01-01',
      endDate: '2026-12-31',
      rate: '8500 PLN brutto',
      generatedDocumentId: 'doc-contract-1',
    },
    {
      id: 'contract-2',
      employeeId: 'u-est',
      employeeName: 'Tomasz Lis',
      positionId: 'pos-2',
      branchId: 'krk',
      type: 'b2b',
      status: 'ending',
      startDate: '2026-02-01',
      endDate: '2026-07-20',
      rate: '12000 PLN netto',
    },
  ],
  trainings: [
    { id: 'tr-1', employeeId: 'u-lead', name: 'Szkolenie BHP', status: 'due_soon', completedAt: '2025-08-01', expiresAt: '2026-07-30' },
    { id: 'tr-2', employeeId: 'u-est', name: 'Standard rozmowy i AI coaching', status: 'valid', completedAt: '2026-03-10', expiresAt: '2027-03-10' },
  ],
  medicalExams: [
    { id: 'med-1', employeeId: 'u-lead', type: 'height', status: 'due_soon', issuedAt: '2025-07-10', expiresAt: '2026-07-10' },
    { id: 'med-2', employeeId: 'u-est', type: 'occupational', status: 'valid', issuedAt: '2026-01-12', expiresAt: '2027-01-12' },
  ],
  certifications: [
    { id: 'cert-1', employeeId: 'u-lead', name: 'Uprawnienia pilarkowe', issuer: 'Forest Safety', status: 'valid', issuedAt: '2025-10-01', expiresAt: '2027-10-01' },
    { id: 'cert-2', employeeId: 'u-est', name: 'Prawo jazdy B', issuer: 'Starostwo', status: 'valid', issuedAt: '2020-05-12', expiresAt: '2035-05-12' },
  ],
};
