/**
 * Stabilne kody błędów dla klientów API (obok polskiego `error`).
 */
module.exports = {
  HTTP_NOT_FOUND: 'HTTP_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_BAD_TOKEN_FORMAT: 'AUTH_BAD_TOKEN_FORMAT',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_FORBIDDEN_EDIT: 'AUTH_FORBIDDEN_EDIT',
  AUTH_BRANCH_ACCESS_DENIED: 'AUTH_BRANCH_ACCESS_DENIED',
  LOGIN_TOO_MANY_ATTEMPTS: 'LOGIN_TOO_MANY_ATTEMPTS',
  LOGIN_INVALID_CREDENTIALS: 'LOGIN_INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PASSWORD_OLD_WRONG: 'PASSWORD_OLD_WRONG',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  /** Błędy przekazane do next(err) z kodem 4xx bez dedykowanego kodu */
  HTTP_CLIENT_ERROR: 'HTTP_CLIENT_ERROR',
  TASK_ACCESS_DENIED: 'TASK_ACCESS_DENIED',
  PAYROLL_SETTLEMENTS_BLOCKED: 'PAYROLL_SETTLEMENTS_BLOCKED',
  TELEFON_PUBLIC_URL_MISSING: 'TELEFON_PUBLIC_URL_MISSING',
  TELEFON_STAFF_PHONE_MISSING: 'TELEFON_STAFF_PHONE_MISSING',
  TELEFON_TWILIO_NOT_CONFIGURED: 'TELEFON_TWILIO_NOT_CONFIGURED',
  TELEFON_TWILIO_FROM_MISSING: 'TELEFON_TWILIO_FROM_MISSING',
  /** Brygadzista / Pomocnik — brak dostępu do połączeń z klientem i listy rozmów */
  TELEFON_TEAM_ROLE_FORBIDDEN: 'TELEFON_TEAM_ROLE_FORBIDDEN',
};
